version: '3.7'

services:
  snackhub-mysql-db-kitchen:
    container_name: snackhub-mysql-db-kitchen
    restart: always
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=pedidos
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  pedidos:
    build: .
    environment:
      - MYSQL_USER=root
      - MYSQL_PW=123456
      - IP_APP=snackhub-mysql-db-kitchen
      - PORT=3306
    ports:
      - 8080:8080
    depends_on:
      - snackhub-mysql-db-kitchen
volumes:
  db_data: