name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Copiar arquivo de propriedades do sonar para a raiz
        run: cp sonar-project.properties .
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=${{ github.workspace }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=grupo60-fiap2023
            -Dsonar.projectKey=snackhub-kitchen
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.python.version=3.12.1