name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch: 
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox -e py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            - name: Configure AWS credentials 🔑
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-region: us-east-1
              aws-access-key-id: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
              aws-secret-access-key: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}    
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ecr_repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) ${{ env.REGISTRY }}
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:kitchen_${{ env.IMAGE_TAG }} -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:kitchen_latest . -f Dockerfile
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:kitchen_${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:kitchen_latest
